banking_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_app.urls')),
    path('', include('banking_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('sign_up/', views.sign_up, name='sign_up'),
]

login_app/models.py
from django.db import models

# Create your models here.
from django.contrib.auth.models import AbstractBaseUser, BaseUserManager



class MyCustomUserManager(BaseUserManager):
    def create_user(self, username, email, first_name, last_name, phone, password):
        if not email:
            raise ValueError('Users must have an email address')
        if not phone:
            raise ValueError('Users must have a phone')
        if not username:
            raise ValueError('Users must have a username')

        user = self.model(
            email=self.normalize_email(email),
            username=username,
            phone=phone,
            password=password,
            last_name=last_name,
            first_name=first_name,
        )

        user.set_password(password)
        user.save(using=self._db)
        return user

    def create_superuser(self, username, first_name, last_name, email, phone, password):
        user = self.create_user(
            username=username,
            email=self.normalize_email(email),
            password=password,
            phone=phone,
            last_name=last_name,
            first_name=first_name,
        )
        user.is_admin = True
        user.is_staff = True
        user.is_superuser = True
        user.save(using=self._db)
        return user


class CustomUser(AbstractBaseUser):
    RANK_CHOICES = (
        ('basic', 'basic'),
        ('silver', 'silver'),
        ('gold', 'gold')
    )
    email = models.EmailField(verbose_name="email", max_length=60, unique=True)
    username = models.CharField(max_length=30, unique=True)
    date_joined = models.DateTimeField(
        verbose_name='date joined', auto_now_add=True)
    last_login = models.DateTimeField(verbose_name='last login', auto_now=True)
    is_admin = models.BooleanField(default=False)
    is_active = models.BooleanField(default=True)
    is_staff = models.BooleanField(default=False)
    is_superuser = models.BooleanField(default=False)
    phone = models.IntegerField(unique=True)
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=30)
    rank = models.CharField(max_length=30, choices=RANK_CHOICES, default='basic')

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email', 'first_name', 'last_name', 'phone']

    objects = MyCustomUserManager()

    def __str__(self):
        return f'{self.username} - {self.email} - {self.phone} - is staff: {self.is_staff} - rank: {self.rank}'

    # For checking permissions. to keep it simple all admin have ALL permissons
    def has_perm(self, perm, obj=None):
        return self.is_admin

    # Does this user have permission to view this app? (ALWAYS YES FOR SIMPLICITY)
    def has_module_perms(self, app_label):
        return True

login_app/views.py
from django.shortcuts import render, reverse
from login_app.models import CustomUser
from django.contrib.auth import authenticate, login as dj_login, logout as dj_logout
from django.http import HttpResponseRedirect


def index(request):
    pass


def login(request):
    context = {}
    if request.method == "POST":
        user = authenticate(
            request, username=request.POST['username'],  password=request.POST['password'], )
        if user:
            dj_login(request, user)
            return HttpResponseRedirect(reverse('banking_app:index'))
        else:
            context = {
                'error': 'Bad username or password.'
            }
    return render(request, 'login_app/login.html', context)


def logout(request):
    dj_logout(request)
    return HttpResponseRedirect(reverse('login_app:login'))


def sign_up(request):
    context = {}
    if request.method == "POST":
        password = request.POST['password']
        confirm_password = request.POST['confirm_password']
        if password == confirm_password:
            if CustomUser.objects.create_user(
                    username=request.POST['username'],
                    first_name=request.POST['first_name'],
                    last_name=request.POST['last_name'],
                    phone=request.POST['phone'],
                    email=request.POST['email'],
                    password=request.POST['password']):
                return HttpResponseRedirect(reverse('login_app:login'))
            else:
                context = {
                    'error': 'Could not create user account - please try again.'
                }
        else:
            context = {
                'error': 'Passwords did not match. Please try again.'
            }
    return render(request, 'login_app/sign_up.html', context)

login_app/templates/login_app/base.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link rel="stylesheet" type="text/css" href="{% static 'banking_app/index.css' %}" media="screen" />
    <title>Banking app</title>
</head>

<body>
    {% block content %} {% endblock %} {% block footer %} {% endblock %}
</body>

</html>

login_app/templates/login_app/login.html
{% extends "login_app/base.html" %} {% block content %}
<header> 
    <h1>Login</h1>
    <a href="{% url 'login_app:sign_up' %}">Sign Up</a>
</header>
<hr />
<div class="div-content">
    <form action="{% url 'login_app:login' %}" method="POST">
        {% csrf_token %}
        <input type="username" name="username" placeholder="User Name"><br>
        <input type="password" name="password" placeholder="Password"><br>
        <button>Login</button>
    </form>
</div>
<hr />

{% if error %}
{{ error }}
{% endif %}

{% endblock %}

login_app/templates/login_app/password_reset.html
{% extends "login_app/base.html" %} {% block content %}

<h1>Reset Password</h1>
<hr />
<form action="{% url 'login_app:password_reset' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="User Name">
    <br />
    <input type="password" name="password" placeholder="New Password">
    <br />
    <input type="password" name="confirm_password" placeholder="Repeat New Password">
    <br />
    <input type="text" name="token" placeholder="Token">
    <br />
    <button>Submit</button>
</form>

{% endblock %}

login_app/templates/login_app/request_password_reset.html
{% extends "login_app/base.html" %} {% block content %}
<h1>Request Password Reset</h1>
<hr />
<form action="{% url 'login_app:request_password_reset' %}" method="POST">
    {% csrf_token %}
    <input type="text" name="username" placeholder="User Name">
    <br />
    <input type="email" name="email" placeholder="Email Address">
    <br />
    <button>Submit</button>
</form>
<hr />
{% endblock %}

login_app/templates/login_app/sign_up.html
{% extends "login_app/base.html" %} {% block content %}
<header> 
    <h1>Sign Up</h1>
    <a href="{% url 'login_app:login' %}">Login</a>
</header> 
<hr />
<div class="div-content">
    <form action="{% url 'login_app:sign_up' %}" method="POST">
        {% csrf_token %}
        <input type="username" name="username" placeholder="User Name"><br>
        <input type="first_name" name="first_name" placeholder="First Name"><br>
        <input type="last_name" name="last_name" placeholder="Last Name"><br>
        <input type="email" name="email" placeholder="Email Address"><br>
        <input type="phone" name="phone" placeholder="Phone Number"><br>
        <input type="password" name="password" placeholder="Password"><br>
        <input type="password" name="confirm_password" placeholder="Confirm Password"><br>
        <button>Sign Up</button>
    </form>
</div>
<hr />
{% if error %}
{{ error }}
{% endif %}

{% endblock %}