banking_app/urls.py
from django.urls import path
from . import views

app_name = 'banking_app'

urlpatterns = [
   path('', views.index, name='index'),
   path('transfer', views.transfer, name='transfer'),
   path('loanpayment', views.loan_payment, name='loanpayment'),
   path('bankaccount/<int:accountno>', views.bankaccount_details, name='bankaccount'),
   path('loan/<int:loanno>', views.loan_details, name='loan'),
   path('profile', views.profile, name='profile'),
]

banking_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('login_app.urls')),
    path('', include('banking_app.urls')),
]

login_app/urls.py
from django.urls import path
from . import views

app_name = 'login_app'

urlpatterns = [
    path('', views.index, name='index'),
    path('login/', views.login, name='login'),
    path('logout/', views.logout, name='logout'),
    path('sign_up/', views.sign_up, name='sign_up'),
]

banking_app/models.py
from django.db import models
from login_app.models import CustomUser
import uuid
import random


def random_string():
    return str(random.randint(100000000000, 999999999999))


class BankAccount(models.Model):
    account_no = models.AutoField(primary_key=True, default=random_string)
    balance = models.DecimalField(max_digits=20, decimal_places=2)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.account_no} - {self.balance} - {self.user.username}'


class Loan(models.Model):
    loan_no = models.AutoField(primary_key=True, default=random_string)
    total_loan = models.DecimalField(max_digits=20, decimal_places=2)
    balance = models.DecimalField(max_digits=20, decimal_places=2)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.loan_no} - {self.total_loan} - {self.balance} - {self.user.username}'


class Transaction(models.Model):
    transaction_id = models.UUIDField(
        primary_key=True, max_length=30, default=uuid.uuid4, editable=False)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    from_account = models.ForeignKey(
        'BankAccount', on_delete=models.CASCADE, related_name='from_account', null=True)
    to_account = models.ForeignKey(
        'BankAccount', on_delete=models.CASCADE, related_name='to_account', null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'amount {self.amount} - {self.timestamp} - {self.transaction_id}'


class LoanPayment(models.Model):
    transaction_id = models.UUIDField(
        primary_key=True, max_length=30, default=uuid.uuid4, editable=False)
    amount = models.DecimalField(max_digits=20, decimal_places=2)
    timestamp = models.DateTimeField(auto_now_add=True)
    from_account = models.ForeignKey(
        'BankAccount', on_delete=models.CASCADE, null=True)
    to_loan = models.ForeignKey('Loan', on_delete=models.CASCADE, null=True)
    user = models.ForeignKey(CustomUser, on_delete=models.CASCADE, null=True)

    def __str__(self):
        return f'amount {self.amount} - {self.timestamp} - {self.transaction_id}'

banking_app/views.py
from django.shortcuts import render, get_object_or_404
from django.db.models import Q
from decimal import Decimal
from django.contrib.auth.decorators import login_required
from .models import BankAccount, Loan, Transaction, LoanPayment

@login_required(login_url='/accounts/login/')
def index(request):
    bankaccounts = BankAccount.objects.filter(user=request.user)
    loans = Loan.objects.filter(user=request.user)
    user_rank = request.user.rank
    context = {'bankaccounts': bankaccounts, 'loans': loans, 'userrank': user_rank}

    if request.method == 'POST':
        loan_amount = request.POST['loan_amount']
        new_loan = Loan()
        new_loan.total_loan = loan_amount
        new_loan.balance = loan_amount
        new_loan.user = request.user
        new_loan.save()

    return render(request, 'banking_app/index.html', context)


@login_required(login_url='/accounts/login/')
def transfer(request):
    allUserAccounts = BankAccount.objects.filter(user=request.user)
    allAccounts = BankAccount.objects.all()
    user_rank = request.user.rank

    if request.method == 'POST':
        amount = request.POST['amount']
        from_account = request.POST['from_account']
        to_account = request.POST['to_account']

        from_account_details = get_object_or_404(BankAccount, account_no=from_account)
        to_account_details = get_object_or_404(BankAccount, account_no=to_account)

        if Decimal(amount) < 0.01:
            context = {
                'message': 'Please enter an amount higher than zero.', 'userrank': user_rank
            }
            return render(request, 'banking_app/confirmation.html', context)

        if from_account == to_account:
            context = {
                'message': 'Cannot transfer to the same account. Try again.', 'userrank': user_rank
            }
            return render(request, 'banking_app/confirmation.html', context)

        if from_account_details.balance < Decimal(amount):
            context = {
                'message': 'Insufficient funds on account.', 'userrank': user_rank
            }
            return render(request, 'banking_app/confirmation.html', context)

        # calculate new balances
        from_account_details.balance = from_account_details.balance - Decimal(amount)
        from_account_details.save()
        to_account_details.balance = to_account_details.balance + Decimal(amount)
        to_account_details.save()

        # create new transaction
        new_transaction = Transaction()
        new_transaction.amount = Decimal(amount)
        new_transaction.from_account = from_account_details
        new_transaction.to_account = to_account_details
        new_transaction.user = request.user
        new_transaction.save()

        context = {
            'message': 'Successfully made the transfer.', 'userrank': user_rank
        }
        return render(request, 'banking_app/confirmation.html', context)


    context = {
        'allUserAccounts': allUserAccounts,
        'allAccounts': allAccounts,
        'userrank': user_rank
    }
    return render(request, 'banking_app/transfer.html', context)


@login_required(login_url='/accounts/login/')
def loan_payment(request):
    allUserAccounts = BankAccount.objects.filter(user=request.user)
    allUserLoans = Loan.objects.filter(user=request.user)

    if request.method == 'POST':
        amount = request.POST['amount']
        from_account = request.POST['from_account']
        to_loan = request.POST['to_loan']

        from_account_details = get_object_or_404(BankAccount, account_no=from_account)
        to_loan_details = get_object_or_404(Loan, loan_no=to_loan)

        if Decimal(amount) < 0.01:
            context = {
                'message': 'Please enter an amount higher than zero.'
            }
            return render(request, 'banking_app/confirmation.html', context)

        if from_account_details.balance < Decimal(amount):
            context = {
                'message': 'Insufficient funds on account.'
            }
            return render(request, 'banking_app/confirmation.html', context)

        # calculate new balances
        from_account_details.balance = from_account_details.balance - Decimal(amount)
        from_account_details.save()
        to_loan_details.balance = to_loan_details.balance - Decimal(amount)
        to_loan_details.save()

        # create new payment
        new_payment = LoanPayment()
        new_payment.amount = Decimal(amount)
        new_payment.from_account = from_account_details
        new_payment.to_loan = to_loan_details
        new_payment.user = request.user
        new_payment.save()

        context = {
            'message': 'Successfully made the payment.'
        }
        return render(request, 'banking_app/confirmation.html', context)


    context = {
        'allUserAccounts': allUserAccounts,
        'allUserLoans': allUserLoans
    }
    return render(request, 'banking_app/loanpayment.html', context)


@login_required(login_url='/accounts/login/')
def bankaccount_details(request, accountno):
    user_rank = request.user.rank
    if BankAccount.objects.filter(account_no=accountno).exists():
        account = get_object_or_404(BankAccount, account_no=accountno)

    transactions = Transaction.objects.filter(Q(from_account=accountno) | Q(to_account=accountno))
    payments = LoanPayment.objects.filter(from_account=accountno)
    alltransactions = transactions.union(payments).order_by('-timestamp')

    context = {
        'account': account,
        'transactions': alltransactions, 
        'userrank': user_rank
    }
    return render(request, 'banking_app/bankaccount.html', context)


@login_required(login_url='/accounts/login/')
def loan_details(request, loanno):
    if Loan.objects.filter(loan_no=loanno).exists():
        loan = get_object_or_404(Loan, loan_no=loanno)

    loanpayments = LoanPayment.objects.filter(to_loan=loanno).order_by('-timestamp')

    context = {
        'loan': loan,
        'loanpayments': loanpayments
    }
    return render(request, 'banking_app/loan.html', context)


@login_required(login_url='/accounts/login/')
def profile(request):
    user_rank = request.user.rank
    user = request.user
    context = {
        'user': user, 'userrank': user_rank
    }
    return render(request, 'banking_app/profile.html', context)

banking_app/templates/banking_app/bankaccount.html
{% extends "banking_app/base.html" %} {% block content %}
<h2>Bank account: {{ account.account_no }}</h2>

<h4>Balance: {{ account.balance }}</h4>

<h4>Transactions:</h4>

{% for transaction in transactions %}
    {% if transaction.from_account.account_no == account.account_no %}
    <div class="transactionRow"><span class="blueText">- {{ transaction.amount }}</span> to 
        {% if transaction.to_account.account_no %}
        account no. {{transaction.to_account.account_no}} ({{transaction.to_account.user.username}}) 
        {% else %}
        loan
        {% endif %} 
        at {{transaction.timestamp|date:'d-m-Y H:i'}}</div>
    {% else %}
    <div class="transactionRow"><span class="blueText">+ {{ transaction.amount }}</span> from account no.
        {{transaction.from_account.account_no}} ({{transaction.from_account.user.username}}) at {{transaction.timestamp|date:'d-m-Y H:i'}}</div>
    {% endif %}
{% endfor %} {% endblock %}

banking_app/templates/banking_app/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    {% load static %}
    <link
      rel="stylesheet"
      type="text/css"
      href="{% static 'banking_app/index.css' %}"
      media="screen"
    />
    <title>Banking app</title>
  </head>

  <body>
    <header>
      <h1>Welcome</h1>
      <nav>
        <a href="{% url 'banking_app:index' %}">Overview</a>
        <a href="{% url 'banking_app:transfer' %}">Transfer</a>
        {% if userrank != 'basic' %}
        <a href="{% url 'banking_app:loanpayment' %}">Loan payment</a>
        {% endif %}
        <a href="{% url 'banking_app:profile' %}">Profile</a>
        <a href="{% url 'login_app:logout' %}">Log out</a>
      </nav>
    </header>
    <hr />
    <div class="div-content">
      {% block content %} {% endblock %} {% block footer %} {% endblock %}
    </div>
  </body>
</html>

banking_app/templates/banking_app/confirmation.html
{% extends "banking_app/base.html" %} {% block content %}
<h3>{{ message }}</h3>

{% endblock %}

banking_app/templates/banking_app/index.html
{% extends "banking_app/base.html" %} {% block content %}
<section class="section-overview">
  <article>
    <h2>My accounts</h2>
    <div class="div-accountRow">
      <span class="bold">Bank account no.</span>
      <span class="bold align-right">Balance</span>
    </div>
    {% for bankaccount in bankaccounts %}
    <div class="div-accountRow">
      <span class="">{{ bankaccount.account_no }}</span>
      <span class="bold align-right">{{ bankaccount.balance }}</span>
      <a href="bankaccount/{{bankaccount.account_no}}">View</a>
    </div>
    {% endfor %}
  </article>

  {% if userrank != 'basic' %}
  <article class="section-loans">
    <h2>My loans</h2>
    <div class="div-loanRow">
      <span class="bold">Loan no.</span>
      <span class="bold align-right">Total loan</span>
      <span class="bold align-right">Rest dept</span>
    </div>
    {% for loan in loans %}
    <div class="div-loanRow">
      <span class="">{{ loan.loan_no }}</span>
      <span class="align-right">{{ loan.total_loan }}</span>
      <span class="align-right">{{ loan.balance }}</span>
      <a href="loan/{{loan.loan_no}}">View</a>
    </div>
    {% endfor %}
    <h3>Start a new loan</h3>
    <form method="POST">
      {% csrf_token %}
      <input class="loanInput" name="loan_amount" type="number" value="0" max="20000"/>
      <button>Start new loan</button>
    </form>
  </article>
{% endif %}
</section>

{% endblock %}

banking_app/templates/banking_app/loan.html
{% extends "banking_app/base.html" %} {% block content %}
<h2>Loan no.: {{ loan.loan_no }}</h2>

<h4>Total loan: {{ loan.total_loan }}</h4>
<h4>Rest loan: {{ loan.balance }}</h4>

<h4>Payments:</h4>

{% for loanpayment in loanpayments %}
<div class="transactionRow">
  <span class="blueText">{{ loanpayment.amount }}</span> from
  {{loanpayment.from_account.account_no}} at {{loanpayment.timestamp|date:'d-m-Y H:i'}}
</div>
{% endfor %} {% endblock %}

banking_app/templates/banking_app/loanpayment.html
{% extends "banking_app/base.html" %} {% block content %}
<h2>Loan payment</h2>

<form method="POST">
  {% csrf_token %}
  <label for="amount">Payment amount:</label>
  <input name="amount" type="number" step="0.01" value="0.00" />
  <label for="from_account">From account:</label>
  <select name="from_account">
    {% for userbankaccount in allUserAccounts %}
    <option value="{{ userbankaccount.account_no }}">
      {{ userbankaccount.account_no }} - {{ userbankaccount.user.username }}
    </option>
    {% endfor %}
  </select>
  <label for="to_loan">To your loan:</label>
  <select name="to_loan">
    {% for userloan in allUserLoans %}
    <option value="{{ userloan.loan_no }}">
      {{ userloan.loan_no }} - rest amount: {{ userloan.balance }}
    </option>
    {% endfor %}
  </select>
  <button>Make loan payment</button>
</form>
{% endblock %}

banking_app/templates/banking_app/profile.html
{% extends "banking_app/base.html" %} {% block content %}
<h2>Profile page</h2>

<div>
    <p><span class="bold">Username:</span> {{user.username}}</p>
    <p><span class="bold">First name:</span> {{user.first_name}}</p>
    <p><span class="bold">Last name:</span> {{user.last_name}}</p>
    <p><span class="bold">Email:</span> {{user.email}}</p>
    <p><span class="bold">Phone no:</span> {{user.phone}}</p>
    <p><span class="bold">Rank:</span> {{user.rank}}</p>

</div>
{% endblock %}

banking_app/templates/banking_app/transfer.html
{% extends "banking_app/base.html" %} {% block content %}
<h2>Transfer</h2>

<form method="POST">
  {% csrf_token %}
  <label for="amount">Transfer amount:</label>
  <input name="amount" type="number" step="0.01" value="0.00" />
  <label for="from_account">From account:</label>
  <select name="from_account">
    {% for userbankaccount in allUserAccounts %}
    <option value="{{ userbankaccount.account_no }}">
      {{ userbankaccount.account_no }} - {{ userbankaccount.user.username }}
    </option>
    {% endfor %}
  </select>
  <label for="to_account">To account:</label>
  <select name="to_account">
    {% for bankaccount in allAccounts %}
    <option value="{{ bankaccount.account_no }}">
      {{ bankaccount.account_no }} - {{ bankaccount.user.username }}
    </option>
    {% endfor %}
  </select>
  <button>Transfer</button>
</form>
{% endblock %}